config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'
  get '/other' => 'index#other' , as: :other
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @content = 'index'
  end

  def other
    @content = 'other'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/index.html.erb
<h1>window.onloadは発動するのか</h1>
<h2>index/index</h2>
<%= link_to 'index/otherへのリンク', other_path %>

<p>
<button id="button">ニャーンボタン</button>
</p>
<p>
<button id="button2">ワンボタン</button>
</p>

<script>
(function(){
  console.log('***index/index beta ***');
})();

$(document).ready(function(){
  console.log('***index/index beta document ready function***');
});

$(window).load(function(){
  console.log('***index/index beta window load function***');
});
</script>

app/views/index/other.html.erb
<h1>window.onloadは発動するのか</h1>
<h2>index/other</h2>
<%= link_to 'index/indexへのリンク', root_path %>

<p>
<button id="button">ニャーンボタン</button>
</p>
<p>
<button id="button2">ワンボタン</button>
</p>

<script>
(function(){
  console.log('***index/other***');
})();

$(document).ready(function(){
  console.log('***index/other beta document ready function***');
});

$(window).load(function(){
  console.log('***index/other beta window load function***');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TurbolinksStudy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content=<%= @content %> />
</head>
<body>

<%= yield %>

</body>
</html>